from enum import StrEnum


class TipoMovimiento(StrEnum):
    INGRESO = "INGRESO"
    SALIDA = "SALIDA"
    AJUSTE_POSITIVO = "AJUSTE_POSITIVO"
    AJUSTE_NEGATIVO = "AJUSTE_NEGATIVO"
    TRANSFERENCIA_SALIDA = "TRANSFERENCIA_SALIDA"
    TRANSFERENCIA_ENTRADA = "TRANSFERENCIA_ENTRADA"


class ReferenciaTipo(StrEnum):
    AJUSTE = "AJUSTE"
    TRANSFERENCIA = "TRANSFERENCIA"
    INGRESO = "INGRESO"
    SALIDA = "SALIDA"
    RECEPCION_COMPRA = "RECEPCION_COMPRA"
